import { URL } from "node:url";

import { OFFICIAL_ENTITIES } from "./official-registry.mjs";

const OFFICIAL = Object.fromEntries(Object.entries(OFFICIAL_ENTITIES).map(([domain, meta]) => [domain, meta.name]));const BRAND_HINTS=Object.entries(OFFICIAL_ENTITIES).flatMap(([domain, meta])=>meta.aliases.map(alias=>[alias,domain]));
const PUBLIC_SUFFIXES=new Set(["co.uk","org.uk","ac.uk","com.au","co.jp"]);
const FREE_MAIL_DOMAINS=new Set(["gmail.com","outlook.com","hotmail.com","live.com","yahoo.com","proton.me","protonmail.com","icloud.com"]);
function similarity(a,b){const s=a.toLowerCase(),t=b.toLowerCase();const d=Array.from({length:t.length+1},(_,i)=>i);for(let i=1;i<=s.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=t.length;j++){const cur=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(s[i-1]===t[j-1]?0:1));prev=cur}}return 1-d[t.length]/Math.max(s.length,t.length,1)}
function rootDomain(hostname){const h=hostname.toLowerCase().replace(/^www\./,"");const p=h.split(".");if(p.length<2)return h;const last2=p.slice(-2).join(".");return PUBLIC_SUFFIXES.has(last2)&&p.length>=3?p.slice(-3).join("."):last2}
function extractUrls(text){const direct=[...text.matchAll(/https?:\/\/[^\s<>'"`]+/gi)].map(m=>m[0].replace(/[),.;!?]+$/,""));const bare=[...text.matchAll(/(?:www\.)[a-z0-9.-]+\.[a-z]{2,}(?:\/[^\s<>'"`]+)?/gi)].map(m=>"https://"+m[0].replace(/[),.;!?]+$/,""));return [...new Set([...direct,...bare])]}
function inspectUrl(raw){try{const u=new URL(raw);const root=rootDomain(u.hostname);const official=OFFICIAL[root];const findings=[];if(u.protocol!=="https:")findings.push("Le lien n'utilise pas HTTPS.");if(u.hostname.includes("xn--"))findings.push("Le domaine utilise une représentation internationale potentiellement trompeuse.");if(u.username||u.password)findings.push("L'URL contient des informations avant le domaine.");if(u.port&&u.port!=="443"&&u.port!=="80")findings.push(`Le lien utilise un port réseau inhabituel (${u.port}).`);if(u.hostname.split(".").length>=5)findings.push("Le domaine comporte un nombre inhabituel de sous-domaines.");if(/^\d{1,3}(\.\d{1,3}){3}$/.test(u.hostname))findings.push("Le lien utilise directement une adresse IP plutôt qu'un domaine.");return{url:raw,host:u.hostname,rootDomain:root,official:official||null,findings}}catch{return{url:raw,host:null,rootDomain:null,official:null,findings:["Le lien ne peut pas être interprété comme une URL valide."]}}}
function extractSender(text){const m=text.match(/(?:^|\n)\s*(?:from|de|expéditeur|sender)\s*:\s*(?:[^<\n]*<)?([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})(?:>)?/i)||text.match(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i);if(!m)return null;const email=m[1]||m[0];const domain=email.split("@")[1]?.toLowerCase()||null;return{email,domain,rootDomain:domain?rootDomain(domain):null}}
function parseHeaders(text){const out={from:null,replyTo:null,returnPath:null,received:[]};for(const line of text.split(/\r?\n/)){const m=line.match(/^\s*(From|De|Expéditeur)\s*:\s*(.+)$/i);if(m)out.from=m[2].trim();const r=line.match(/^\s*(Reply-To|Répondre à)\s*:\s*(.+)$/i);if(r)out.replyTo=r[2].trim();const p=line.match(/^\s*(Return-Path)\s*:\s*(.+)$/i);if(p)out.returnPath=p[2].trim();if(/^\s*Received\s*:/i.test(line))out.received.push(line.trim())}return out}\nfunction detectHomoglyphs(value){return /[\u0400-\u04FF\u0370-\u03FF\u2000-\u206F]/u.test(value)}\nfunction inferIntent(text){const l=text.toLowerCase();if(/carte bancaire|numéro de carte|cvv|cryptogramme|virement|paiement|payez|frais|€/.test(l))return"finance";if(/mot de passe|identifiant|connexion|code de sécurité|otp|double authentification/.test(l))return"credentials";if(/colis|livraison|chronopost|laposte|mondial relay/.test(l))return"delivery";if(/impôt|amende|caf|ameli|france travail|urssaf|remboursement|administratif/.test(l))return"administrative";if(/urgent|immédiat|suspendu|bloqué|dernière chance/.test(l))return"pressure";return"generic"}
export function analyzeMessage(text){
 const urls=extractUrls(text).map(inspectUrl);const sender=extractSender(text);const headers=parseHeaders(text);const lower=text.toLowerCase();const reasons=[];let risk=0;
 if(urls.length){reasons.push(`${urls.length} lien${urls.length>1?"s":""} détecté${urls.length>1?"s":""}.`);risk+=1}
 if(/bit\.ly|tinyurl\.com|t\.co|goo\.gl|ow\.ly|is\.gd|cutt\.ly|shorturl\.at/i.test(text)){reasons.push("Un service de raccourcissement d'URL est présent.");risk+=2}
 if(/data:text\/html|javascript:/i.test(text)){reasons.push("Le contenu contient un schéma d'URL exécutable.");risk+=4}
 if(urls.some(u=>/[?&](redirect|url|target|dest)=/i.test(u.url))){reasons.push("Un lien contient un paramètre de redirection.");risk+=1}
 if(/paiement|payez|virement|carte bancaire|frais|2[,.]?\d+\s*€/.test(lower)){reasons.push("Le contenu évoque un paiement ou une demande financière.");risk+=2}
 if(/urgent|immédiat|dans\s+\d+\s*(min|minute|h|heure|jour)|dernière chance|suspendu|bloqué/.test(lower)){reasons.push("Le contenu crée une pression temporelle ou une menace de blocage.");risk+=2}
 if(/mot de passe|code|identifiant|connexion|numéro de carte|cryptogramme|cvv/.test(lower)){reasons.push("Le contenu évoque des informations d'authentification ou bancaires.");risk+=2}
 const claimed=BRAND_HINTS.find(([hint])=>lower.includes(hint));let identity={claimedBrand:claimed?OFFICIAL[claimed[1]]:null,officialDomain:claimed?claimed[1]:null,sender:sender?.email||null,senderDomain:sender?.rootDomain||null,status:"unknown"};
 if(claimed&&sender?.rootDomain){if(sender.rootDomain===claimed[1])identity.status="official";else{const score=similarity(sender.rootDomain,claimed[1]);identity.status=score>=0.72?"lookalike":"mismatch";reasons.push(`L'expéditeur utilise « ${sender.rootDomain} » alors que le domaine officiel attendu est « ${claimed[1]} ».`);risk+=identity.status==="lookalike"?3:2}} 
 if(claimed&&!sender){identity.status="unknown";reasons.push(`L'organisme « ${claimed[0]} » est cité, mais aucune adresse d'expéditeur exploitable n'a été fournie.`);risk+=1}
 if(sender?.rootDomain&&FREE_MAIL_DOMAINS.has(sender.rootDomain)&&claimed){reasons.push("L'expéditeur utilise une messagerie grand public alors qu'il se présente comme un organisme identifié.");risk+=1}
 if(!claimed&&sender)identity={...identity,status:OFFICIAL[sender.rootDomain]?"official":"unknown"};
 if(claimed&&urls.length&&!urls.some(u=>u.rootDomain===claimed[1])){reasons.push(`Le message cite « ${claimed[0]} » mais aucun lien ne correspond au domaine officiel ${claimed[1]}.`);risk+=3}
 for(const u of urls){if(u.rootDomain&&!OFFICIAL[u.rootDomain]){const near=Object.keys(OFFICIAL).filter(d=>d.length>=8).map(d=>({d,score:similarity(u.rootDomain,d)})).sort((a,b)=>b.score-a.score)[0];if(near&&near.score>=0.72){reasons.push(`Le domaine « ${u.rootDomain} » ressemble à « ${near.d} » sans être le domaine officiel.`);risk+=3}}}
 if(headers.replyTo&&sender?.email&&headers.replyTo.toLowerCase()!==sender.email.toLowerCase()){reasons.push("Le champ Reply-To diffère de l’expéditeur détecté.");risk+=2}\nif(sender?.domain&&detectHomoglyphs(sender.domain)){reasons.push("Le domaine de l’expéditeur contient des caractères Unicode potentiellement trompeurs.");risk+=3}\nfor(const u of urls)for(const f of u.findings){reasons.push(f);risk+=2}
 const intent=inferIntent(text);
 let verdict="ok",title="Aucun signal préoccupant détecté",confidence="faible";
 if(risk>=7){verdict="stop";title="N'agis pas tout de suite";confidence="élevée"}else if(risk>=4){verdict="caution";title="Prudence";confidence="moyenne"}else if(risk>=1){verdict="check";title="À vérifier";confidence="moyenne"}
 const summary=verdict==="stop"?"Plusieurs signaux compatibles avec une tentative de fraude ont été détectés.":verdict==="caution"?"Plusieurs éléments méritent une vérification indépendante.":verdict==="check"?"Un élément mérite une vérification avant d'agir.":"Aucun signal de risque évident n'a été identifié dans le contenu fourni.";
 const actions=verdict==="stop"?["N'utilise pas le lien reçu.","Ouvre toi-même le site ou l'application officielle.","Ne communique aucun code, mot de passe ou donnée bancaire."]:verdict==="caution"?["N'agis pas depuis le message.","Vérifie l'organisme par un canal indépendant."]:["Compare le contenu avec la source officielle avant d'agir."];
 const evidence={urls:urls.map(u=>u.url),sender:sender?.email||null,senderDomain:sender?.rootDomain||null,officialDomain:claimed?.[1]||null,intent,risk,headers:{from:headers.from,replyTo:headers.replyTo,returnPath:headers.returnPath,receivedCount:headers.received.length},urlFindings:urls.flatMap(u=>u.findings)};
 return{verdict,title,summary,confidence,reasons,actions,urls,identity,intent,evidence,checkedAt:new Date().toISOString(),engine:"rules-v0.4"};
}

import { getAiSecondOpinion, mergeAiOpinion } from "./ai.mjs";
export async function analyzeMessageWithAI(text){const deterministic=analyzeMessage(text);const ai=await getAiSecondOpinion(text,deterministic);return mergeAiOpinion(deterministic,ai);}
