import { useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronLeft, Clipboard, Link2, Paperclip, ScanLine, ShieldAlert, ShieldCheck, Upload, LoaderCircle } from "lucide-react";
import { analyzeText, type Analysis, type Verdict } from "./lib/analyze";

const verdictMeta:Record<Verdict,{icon:any;label:string;className:string}>={ok:{icon:CheckCircle2,label:"OK",className:"ok"},check:{icon:AlertTriangle,label:"À VÉRIFIER",className:"check"},caution:{icon:ShieldAlert,label:"PRUDENCE",className:"caution"},stop:{icon:ShieldAlert,label:"STOP",className:"stop"}};

type ServerAnalysis=Analysis & { urls?:Array<{url:string;host:string|null;rootDomain:string|null;official:string|null;findings:string[]}>; engine?:string };

export function App(){
 const [input,setInput]=useState(""); const [analysis,setAnalysis]=useState<ServerAnalysis|null>(null); const [history,setHistory]=useState<string[]>([]); const [loading,setLoading]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const placeholder=useMemo(()=>"Colle ici un SMS, un e-mail, un lien ou le texte d'une capture…",[]);
 async function verify(value=input){
  const clean=value.trim(); if(!clean)return; setInput(clean); setLoading(true);
  try{const r=await fetch((import.meta.env.VITE_API_URL||"")+"/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:clean})}); if(!r.ok)throw new Error(); setAnalysis(await r.json());}
  catch{setAnalysis({...analyzeText(clean),engine:"local-fallback"});}
  finally{setLoading(false);setHistory(h=>[clean.slice(0,80),...h.filter(x=>x!==clean)].slice(0,10));}
 }
 function onFile(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>{const value=String(reader.result||"");if(file.type.startsWith("text/"))setInput(value);else setAnalysis({verdict:"check",title:"Image reçue",summary:"La photo est bien reçue. L'OCR automatique sera activé dans la prochaine brique du moteur.",reasons:["Le fichier image a été reçu."],actions:["Ne transmets pas d'information sensible avant vérification."],confidence:"faible",engine:"image-input"});}; if(file.type.startsWith("text/"))reader.readAsText(file); else reader.readAsDataURL(file);}
 const M=analysis?verdictMeta[analysis.verdict]:null; const Icon=M?.icon;
 return <div className="app"><header className="topbar"><div className="brand">VÉRIF</div><span className="tagline">Un doute ? Vérifie avant d'agir.</span></header><main>
 {!analysis?<><section className="hero"><div className="eyebrow">PROTECTION DU QUOTIDIEN</div><h1>Un doute ?</h1><p>Montre-moi ce que tu as reçu. VÉRIF analyse les signaux visibles avant que tu agisses.</p><div className="card composer"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={placeholder} aria-label="Contenu à vérifier"/><div className="tools"><button onClick={()=>fileRef.current?.click()} className="tool"><Upload size={18}/>Importer</button><button onClick={()=>navigator.clipboard?.readText().then(t=>setInput(t))} className="tool"><Clipboard size={18}/>Coller</button><button onClick={()=>setInput("https://")} className="tool"><Link2 size={18}/>Lien</button><button onClick={()=>fileRef.current?.click()} className="tool"><ScanLine size={18}/>Photo</button><input ref={fileRef} type="file" accept="image/*,text/plain,.txt" hidden onChange={e=>onFile(e.target.files?.[0])}/></div><button disabled={!input.trim()||loading} onClick={()=>verify()} className="primary">{loading?<><LoaderCircle className="spin" size={18}/> ANALYSE…</>:"VÉRIFIER"}</button></div><div className="trust"><ShieldCheck size={18}/><span>Contrôles explicables • L'IA ne décide pas seule • « Je ne sais pas » reste possible</span></div></section>{history.length>0&&<section className="history"><h3>Récentes</h3>{history.map((h,i)=><button key={i} onClick={()=>verify(h)}><Paperclip size={15}/>{h}</button>)}</section>}</>:
 <section className="result"><button className="back" onClick={()=>setAnalysis(null)}><ChevronLeft size={20}/>Nouvelle vérification</button><div className={`resultCard ${M.className}`}><div className="resultHead"><div className="stateIcon"><Icon size={30}/></div><div><div className="stateLabel">{M.label}</div><h2>{analysis.title}</h2><p>{analysis.summary}</p></div></div><div className="grid2"><div className="panel"><h3>Pourquoi ?</h3><ul>{analysis.reasons.map((r,i)=><li key={i}>{r}</li>)}</ul></div><div className="panel"><h3>Que faire ?</h3><ul>{analysis.actions.map((r,i)=><li key={i}>{r}</li>)}</ul></div></div>{analysis.urls?.length>0&&<div className="panel links"><h3>Liens détectés</h3>{analysis.urls.map((u,i)=><div key={i}><b>{u.host||"Lien invalide"}</b>{u.official&&<span> · domaine officiel reconnu : {u.official}</span>}{u.findings.map((f,j)=><div key={j}>{f}</div>)}</div>)}</div>}<div className="confidence">Confiance : <strong>{analysis.confidence}</strong> · moteur : <strong>{analysis.engine||"local"}</strong></div>{analysis.verdict!=="ok"&&<button className="secondary">VÉRIFIER AUTREMENT</button>}</div><div className="card inputAgain"><textarea value={input} onChange={e=>setInput(e.target.value)}/><button className="primary" onClick={()=>verify()} disabled={loading}>REFAIRE</button></div></section>}
 </main><footer>VÉRIF aide à vérifier. Il ne garantit jamais qu'un contenu est sûr.</footer></div>;
}
